#!/usr/bin/env bash

###
### download_file function are AI generated by GPT-OSS 120B
###
### START
###
### Prompt
###
### write me a bash script segment to check if a curl download of file on a URL fail,
### then proceed to download again, with a retry of 5 times. If after 5 retries and is unsuccessful.
### report that file download failed and exit the script.
###
### Response
###
### <> bash
###
### #!/usr/bin/env bash
###
### URL="https://example.com/path/to/file"
### OUTPUT="file.bin"
### MAX_RETRIES=5
### attempt=0
###
### while (( attempt < MAX_RETRIES )); do
###     ((attempt++))
###     echo "Attempt $attempt of $MAX_RETRIES..."
###
###     # -f: fail silently on HTTP errors
###     # -L: follow redirects
###     # -o: write output to file
###     curl -fL "$URL" -o "$OUTPUT"
###     status=$?
###
###     if [[ $status -eq 0 ]]; then
###         echo "Download succeeded."
###         break
###     else
###         echo "Download failed (curl exit code $status)."
###         # optional: wait before retrying
###         sleep 2
###     fi
### done
###
### if [[ $status -ne 0 ]]; then
###     echo "Error: file download failed after $MAX_RETRIES attempts."
###     exit 1
### fi
###
### # continue with the rest of the script...
###
### Prompt
###
### convert the above script segment into a bash function
###
### Response
###
### <> bash
###
### #!/usr/bin/env bash
###
### download_file() {
###     local url="$1"
###     local output="$2"
###     local max_retries="${3:-5}"
###     local attempt=0
###     local status=0
###
###     while (( attempt < max_retries )); do
###         ((attempt++))
###         echo "Attempt $attempt of $max_retries..."
###
###         curl -fL "$url" -o "$output"
###         status=$?
###
###         if (( status == 0 )); then
###             echo "Download succeeded."
###             return 0
###         else
###             echo "Download failed (curl exit code $status)."
###             sleep 2   # optional pause before next try
###         fi
###     done
###
###     echo "Error: file download failed after $max_retries attempts."
###     return 1
### }
###
### # Example usage:
### # download_file "https://example.com/path/to/file" "file.bin" 5
### # if [[ $? -ne 0 ]]; then
### #     exit 1
### # fi
###
### Prompt
###
### should 'while (( attempt < max_retries )); do' be written as 'while [[ $attempt < $max_retries ]]; do' ?
###
### Response
###
### Both forms work, but they have different semantics:
### Form	                                    Evaluation method	                Numeric vs. string handling	                                                                            Typical use
### while (( attempt < max_retries )); do	    Arithmetic evaluation ((( … )))	    Treated strictly as integers	                                                                        Preferred for pure numeric counters
### while [[ $attempt < $max_retries ]]; do	    Conditional expression ([[ … ]])	< is a lexicographic string comparison unless both operands are explicitly forced to numeric (-lt)	    Less clear for numeric loops and can give unexpected results if the values contain leading zeros or non‑numeric characters
###
### <> Bash
###
### while [[ $attempt -lt $max_retries ]]; do
###     …
### done
###
### But the original (( … )) version is simpler and less error‑prone for this use case.
###
### END


download_file() {
    local url="$1"
    local output="$2"
    local max_retries="${3:-5}"
    local attempt=0
    local status=0

    while (( attempt < max_retries )); do
        ((attempt++))
        echo "Attempt $attempt of $max_retries..."

        curl -fL "$url" -o "$output"
        status=$?

        if (( status == 0 )); then
            echo "Download succeeded."
            return 0
        else
            echo "Download failed (curl exit code $status)."
            sleep 2   # optional pause before next try
        fi
    done

    echo "Error: file download failed after $max_retries attempts."
    return 1
}

mkdir -p ~/.kube
mkdir -p ~/.config/eget
mkdir -p ~/.local/bin
mkdir -p ~/Projects/kind

URL="https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
OUTPUT="$HOME/.local/bin/kubectl"
download_file "$URL" "$OUTPUT"

chmod +x "$HOME/.local/bin/kubectl"

URL="https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64"
OUTPUT="$HOME/.local/bin/minikube"
download_file "$URL" "$OUTPUT"

chmod +x "$HOME/.local/bin/minikube"

cp ./eget.toml ~/.config/eget
./eget.sh

mkdir -p "$HOME/.config" && touch "$HOME/.config/starship.toml"
cat <<'EOF' | tee "$HOME/.config/starship.toml"
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[docker_context]
disabled = true

[container]
disabled = true
EOF

cat <<'EOF' >>"$HOME/.bashrc"

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    export PATH="$HOME/.local/bin:$PATH"
fi
# fzf
if command -v fzf > /dev/null; then
    eval "$(fzf --bash)"
fi
# direnv
if command -v direnv > /dev/null; then
    eval "$(direnv hook bash)"
fi
# zoxdie
if command -v zoxdie > /dev/null; then
 eval "$(zoxide init zsh --cmd cd)"
fi
# OpenTofu
if command -v tofu > /dev/null; then
    complete -o nospace -C /usr/bin/tofu tofu
fi
# Teraform
if command -v terraform > /dev/null; then
    complete -o nospace -C /usr/bin/terraform terraform
fi
# Starship
starship_enabled=false
if command -v starship > /dev/null && [[ "$starship_enabled" == "true" ]]; then
    eval "$(starship init bash)"
    source <(starship completions bash)
fi
#
# Aliases
#
# bat
if command -v bat > /dev/null; then
    alias less=bat
fi
EOF

source ~/.bashrc

"$HOME/.local/bin/eget" -D

tar -C ./projects-kind --exclude="kind.yaml" -cvf - . | tar -C ~/Projects/kind -xvf -

tar -C ./local-bin --exclude="cert-manager.sh" -cvf - . | tar -C ~/.local/bin -xvf -

tar -C ./dot-kube -cvf - . | tar -C ~/.kube -xvf -

ln -s ~/.local/bin/kubectl ~/.local/bin/k

export DEBIAN_FRONTEND=noninteractive
sudo apt install byobu nfs-kernel-server -y

echo "/srv 10.254.254.0/24(rw,async,no_subtree_check,no_root_squash)" | sudo tee /etc/exports

sudo exportfs -a

cat ./versions.rc >> ~/.bashrc

cat ./projects-kind/bashrc >> ~/.bashrc

source ./versions.rc

envsubst '$DH_NAMESPACE:$KINDEST_NODE_VER' < projects-kind/kind.yaml | tee ~/Projects/kind/kind-$(echo ${KINDEST_NODE_VER%@sha*}).yaml
envsubst '$CERT_MANAGER_VER' < ./local-bin/cert-manager.sh > ~/.local/bin/cert-manager.sh
chmod +x ~/.local/bin/cert-manager.sh

"$HOME/.local/bin/docker-network-kind.sh"

pip install pipx
"$HOME/.local/bin/pipx" install rundoc