alias k=kubectl
alias e=exit
if command -v kubectl > /dev/null; then
    source <(k completion bash)
    complete -o default -F __start_kubectl k
fi
if command -v kustomize > /dev/null; then
    source <(kustomize completion bash)
fi
if command -v kind > /dev/null; then
    source <(kind completion bash)
fi
if command -v k9s > /dev/null; then
    source <(k9s completion bash)
fi
if command -v helm > /dev/null; then
    source <(helm completion bash)
fi
if command -v cilium > /dev/null; then
    source <(cilium completion bash)
fi
if command -v yq > /dev/null; then
    source <(yq shell-completion bash)
fi
if command -v gwctl > /dev/null; then
    source <(gwctl completion bash)
fi
